version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Docker/Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
